/**
 * @file
 * @author Tomáš Chochola <tomaschochola@tomaschochola.cz>
 * @copyright © 2026 Tomáš Chochola <tomaschochola@tomaschochola.cz>
 *
 * @license CC-BY-ND-4.0
 *
 * @see {@link https://creativecommons.org/licenses/by-nd/4.0/} License
 * @see {@link https://github.com/tomaschochola} GitHub Profile
 * @see {@link https://github.com/sponsors/tomaschochola} GitHub Sponsors
 */

import { ExpressiveTypographyEnum } from '../enums';
import { expressiveTokens } from './tokens';

export const expressivePresets = {
  base: {
    button: {
      borderBottomStyle: 'none',
      borderLeftStyle: 'none',
      borderRightStyle: 'none',
      borderTopStyle: 'none',
      outlineStyle: 'none',
      paddingBottom: '0px',
      paddingLeft: '0px',
      paddingRight: '0px',
      paddingTop: '0px',
    },
    anchor: {
      color: 'inherit',
      textDecorationLine: 'none',
      borderBottomStyle: 'none',
      borderLeftStyle: 'none',
      borderRightStyle: 'none',
      borderTopStyle: 'none',
      outlineStyle: 'none',
      paddingBottom: '0px',
      paddingLeft: '0px',
      paddingRight: '0px',
      paddingTop: '0px',
    },
    border: {
      borderBottomColor: expressiveTokens['md.sys.color.outline'],
      borderBottomStyle: 'solid',
      borderLeftColor: expressiveTokens['md.sys.color.outline'],
      borderLeftStyle: 'solid',
      borderRightColor: expressiveTokens['md.sys.color.outline'],
      borderRightStyle: 'solid',
      borderTopColor: expressiveTokens['md.sys.color.outline'],
      borderTopStyle: 'solid',
    },
    ellipsis: {
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      overflowX: 'hidden',
      overflowY: 'hidden',
    },
    oneliner: {
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      lineHeight: 1,
      overflowX: 'hidden',
      overflowY: 'hidden',
    },
  },
  disabled: {
    content: {
      color: `oklch(from ${expressiveTokens['md.sys.color.on-surface-variant']} l c h / ${expressiveTokens['md.sys.opacity.disabled-content']})`,
    },
    container: {
      backgroundColor: `oklch(from ${expressiveTokens['md.sys.color.on-surface-variant']} l c h / ${expressiveTokens['md.sys.opacity.disabled-container']})`,
    },
    outline: {
      borderBottomColor: `oklch(from ${expressiveTokens['md.sys.color.on-surface-variant']} l c h / ${expressiveTokens['md.sys.opacity.disabled-outline']})`,
      borderLeftColor: `oklch(from ${expressiveTokens['md.sys.color.on-surface-variant']} l c h / ${expressiveTokens['md.sys.opacity.disabled-outline']})`,
      borderRightColor: `oklch(from ${expressiveTokens['md.sys.color.on-surface-variant']} l c h / ${expressiveTokens['md.sys.opacity.disabled-outline']})`,
      borderTopColor: `oklch(from ${expressiveTokens['md.sys.color.on-surface-variant']} l c h / ${expressiveTokens['md.sys.opacity.disabled-outline']})`,
    },
  },
  font: {
    [ExpressiveTypographyEnum.DisplayLarge]: {
      fontFamily: expressiveTokens['md.sys.typography.display-large.font-family'],
      fontSize: expressiveTokens['md.sys.typography.display-large.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.display-large.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.display-large.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.display-large.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.display-large.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.display-large.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.display-large.text-transform'],
    },
    [ExpressiveTypographyEnum.DisplayMedium]: {
      fontFamily: expressiveTokens['md.sys.typography.display-medium.font-family'],
      fontSize: expressiveTokens['md.sys.typography.display-medium.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.display-medium.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.display-medium.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.display-medium.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.display-medium.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.display-medium.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.display-medium.text-transform'],
    },
    [ExpressiveTypographyEnum.DisplaySmall]: {
      fontFamily: expressiveTokens['md.sys.typography.display-small.font-family'],
      fontSize: expressiveTokens['md.sys.typography.display-small.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.display-small.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.display-small.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.display-small.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.display-small.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.display-small.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.display-small.text-transform'],
    },
    [ExpressiveTypographyEnum.HeadlineLarge]: {
      fontFamily: expressiveTokens['md.sys.typography.headline-large.font-family'],
      fontSize: expressiveTokens['md.sys.typography.headline-large.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.headline-large.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.headline-large.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.headline-large.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.headline-large.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.headline-large.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.headline-large.text-transform'],
    },
    [ExpressiveTypographyEnum.HeadlineMedium]: {
      fontFamily: expressiveTokens['md.sys.typography.headline-medium.font-family'],
      fontSize: expressiveTokens['md.sys.typography.headline-medium.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.headline-medium.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.headline-medium.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.headline-medium.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.headline-medium.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.headline-medium.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.headline-medium.text-transform'],
    },
    [ExpressiveTypographyEnum.HeadlineSmall]: {
      fontFamily: expressiveTokens['md.sys.typography.headline-small.font-family'],
      fontSize: expressiveTokens['md.sys.typography.headline-small.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.headline-small.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.headline-small.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.headline-small.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.headline-small.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.headline-small.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.headline-small.text-transform'],
    },
    [ExpressiveTypographyEnum.TitleLarge]: {
      fontFamily: expressiveTokens['md.sys.typography.title-large.font-family'],
      fontSize: expressiveTokens['md.sys.typography.title-large.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.title-large.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.title-large.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.title-large.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.title-large.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.title-large.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.title-large.text-transform'],
    },
    [ExpressiveTypographyEnum.TitleMedium]: {
      fontFamily: expressiveTokens['md.sys.typography.title-medium.font-family'],
      fontSize: expressiveTokens['md.sys.typography.title-medium.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.title-medium.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.title-medium.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.title-medium.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.title-medium.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.title-medium.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.title-medium.text-transform'],
    },
    [ExpressiveTypographyEnum.TitleSmall]: {
      fontFamily: expressiveTokens['md.sys.typography.title-small.font-family'],
      fontSize: expressiveTokens['md.sys.typography.title-small.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.title-small.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.title-small.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.title-small.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.title-small.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.title-small.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.title-small.text-transform'],
    },
    [ExpressiveTypographyEnum.BodyLarge]: {
      fontFamily: expressiveTokens['md.sys.typography.body-large.font-family'],
      fontSize: expressiveTokens['md.sys.typography.body-large.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.body-large.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.body-large.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.body-large.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.body-large.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.body-large.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.body-large.text-transform'],
    },
    [ExpressiveTypographyEnum.BodyMedium]: {
      fontFamily: expressiveTokens['md.sys.typography.body-medium.font-family'],
      fontSize: expressiveTokens['md.sys.typography.body-medium.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.body-medium.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.body-medium.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.body-medium.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.body-medium.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.body-medium.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.body-medium.text-transform'],
    },
    [ExpressiveTypographyEnum.BodySmall]: {
      fontFamily: expressiveTokens['md.sys.typography.body-small.font-family'],
      fontSize: expressiveTokens['md.sys.typography.body-small.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.body-small.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.body-small.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.body-small.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.body-small.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.body-small.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.body-small.text-transform'],
    },
    [ExpressiveTypographyEnum.LabelLarge]: {
      fontFamily: expressiveTokens['md.sys.typography.label-large.font-family'],
      fontSize: expressiveTokens['md.sys.typography.label-large.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.label-large.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.label-large.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.label-large.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.label-large.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.label-large.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.label-large.text-transform'],
    },
    [ExpressiveTypographyEnum.LabelMedium]: {
      fontFamily: expressiveTokens['md.sys.typography.label-medium.font-family'],
      fontSize: expressiveTokens['md.sys.typography.label-medium.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.label-medium.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.label-medium.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.label-medium.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.label-medium.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.label-medium.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.label-medium.text-transform'],
    },
    [ExpressiveTypographyEnum.LabelSmall]: {
      fontFamily: expressiveTokens['md.sys.typography.label-small.font-family'],
      fontSize: expressiveTokens['md.sys.typography.label-small.font-size'],
      fontStyle: expressiveTokens['md.sys.typography.label-small.font-style'],
      fontWeight: expressiveTokens['md.sys.typography.label-small.font-weight'],
      letterSpacing: expressiveTokens['md.sys.typography.label-small.letter-spacing'],
      lineHeight: expressiveTokens['md.sys.typography.label-small.line-height'],
      textDecoration: expressiveTokens['md.sys.typography.label-small.text-decoration'],
      textTransform: expressiveTokens['md.sys.typography.label-small.text-transform'],
    },
  },
  transition: {
    spatialFast: {
      transitionDuration: expressiveTokens['md.sys.duration.spatial-fast'],
      transitionTimingFunction: expressiveTokens['md.sys.timing-function.spatial-fast'],
    },
    spatialDefault: {
      transitionDuration: expressiveTokens['md.sys.duration.spatial-default'],
      transitionTimingFunction: expressiveTokens['md.sys.timing-function.spatial-default'],
    },
    spatialSlow: {
      transitionDuration: expressiveTokens['md.sys.duration.spatial-slow'],
      transitionTimingFunction: expressiveTokens['md.sys.timing-function.spatial-slow'],
    },
    effectsFast: {
      transitionDuration: expressiveTokens['md.sys.duration.effects-fast'],
      transitionTimingFunction: expressiveTokens['md.sys.timing-function.effects-fast'],
    },
    effectsDefault: {
      transitionDuration: expressiveTokens['md.sys.duration.effects-default'],
      transitionTimingFunction: expressiveTokens['md.sys.timing-function.effects-default'],
    },
    effectsSlow: {
      transitionDuration: expressiveTokens['md.sys.duration.effects-slow'],
      transitionTimingFunction: expressiveTokens['md.sys.timing-function.effects-slow'],
    },
  },
} as const;
