/**
 * @file
 * @author Tomáš Chochola <tomaschochola@tomaschochola.cz>
 * @copyright © 2026 Tomáš Chochola <tomaschochola@tomaschochola.cz>
 *
 * @license CC-BY-ND-4.0
 *
 * @see {@link https://creativecommons.org/licenses/by-nd/4.0/} License
 * @see {@link https://github.com/tomaschochola} GitHub Profile
 * @see {@link https://github.com/sponsors/tomaschochola} GitHub Sponsors
 */

export const expressiveQueries = {
  compact: 'screen and (max-width: 599px)',
  medium: 'screen and (min-width: 600px) and (max-width: 839px)',
  expanded: 'screen and (min-width: 840px) and (max-width: 1199px)',
  large: 'screen and (min-width: 1200px) and (max-width: 1599px)',
  extraLarge: 'screen and (min-width: 1600px)',
  portrait: '(orientation: portrait)',
  landscape: '(orientation: landscape)',
  phone: 'screen and (max-width: 599px)',
  tablet: 'screen and (min-width: 600px) and (max-width: 1199px)',
  desktop: 'screen and (min-width: 1200px)',
  prefersDark: '(prefers-color-scheme: dark)',
  prefersReduceMotion: '(prefers-reduced-motion: reduce)',
} as const;

export const expressiveTokens = {
  'md.sys.corner.radius.full': 'var(--md-sys-corner-radius-full)',
  'md.sys.corner.radius.extra-extra-large': 'var(--md-sys-corner-radius-extra-extra-large)',
  'md.sys.corner.radius.extra-large-increased': 'var(--md-sys-corner-radius-extra-large-increased)',
  'md.sys.corner.radius.extra-large': 'var(--md-sys-corner-radius-extra-large)',
  'md.sys.corner.radius.large-increased': 'var(--md-sys-corner-radius-large-increased)',
  'md.sys.corner.radius.large': 'var(--md-sys-corner-radius-large)',
  'md.sys.corner.radius.medium': 'var(--md-sys-corner-radius-medium)',
  'md.sys.corner.radius.small': 'var(--md-sys-corner-radius-small)',
  'md.sys.corner.radius.extra-small': 'var(--md-sys-corner-radius-extra-small)',
  'md.sys.corner.radius.none': 'var(--md-sys-corner-radius-none)',
  'md.sys.motion.easing.spatial-fast': 'var(--md-sys-motion-easing-spatial-fast)',
  'md.sys.motion.easing.spatial': 'var(--md-sys-motion-easing-spatial)',
  'md.sys.motion.easing.spatial-slow': 'var(--md-sys-motion-easing-spatial-slow)',
  'md.sys.motion.easing.effects-fast': 'var(--md-sys-motion-easing-effects-fast)',
  'md.sys.motion.easing.effects': 'var(--md-sys-motion-easing-effects)',
  'md.sys.motion.easing.effects-slow': 'var(--md-sys-motion-easing-effects-slow)',
  'md.sys.motion.duration.short1': 'var(--md-sys-motion-duration-short1)',
  'md.sys.motion.duration.short2': 'var(--md-sys-motion-duration-short2)',
  'md.sys.motion.duration.short3': 'var(--md-sys-motion-duration-short3)',
  'md.sys.motion.duration.short4': 'var(--md-sys-motion-duration-short4)',
  'md.sys.motion.duration.medium1': 'var(--md-sys-motion-duration-medium1)',
  'md.sys.motion.duration.medium2': 'var(--md-sys-motion-duration-medium2)',
  'md.sys.motion.duration.medium3': 'var(--md-sys-motion-duration-medium3)',
  'md.sys.motion.duration.medium4': 'var(--md-sys-motion-duration-medium4)',
  'md.sys.motion.duration.long1': 'var(--md-sys-motion-duration-long1)',
  'md.sys.motion.duration.long2': 'var(--md-sys-motion-duration-long2)',
  'md.sys.motion.duration.long3': 'var(--md-sys-motion-duration-long3)',
  'md.sys.motion.duration.long4': 'var(--md-sys-motion-duration-long4)',
  'md.sys.motion.duration.extra-long1': 'var(--md-sys-motion-duration-extra-long1)',
  'md.sys.motion.duration.extra-long2': 'var(--md-sys-motion-duration-extra-long2)',
  'md.sys.motion.duration.extra-long3': 'var(--md-sys-motion-duration-extra-long3)',
  'md.sys.motion.duration.extra-long4': 'var(--md-sys-motion-duration-extra-long4)',
  'md.sys.opacity.state.pressed': 'var(--md-sys-opacity-state-pressed)',
  'md.sys.opacity.state.focused': 'var(--md-sys-opacity-state-focused)',
  'md.sys.opacity.state.hovered': 'var(--md-sys-opacity-state-hovered)',
  'md.sys.opacity.state.dragged': 'var(--md-sys-opacity-state-dragged)',
  'md.sys.opacity.layer.scrim': 'var(--md-sys-opacity-layer-scrim)',
  'md.sys.opacity.layer.shadow': 'var(--md-sys-opacity-layer-shadow)',
  'md.sys.opacity.disabled.content': 'var(--md-sys-opacity-disabled-content)',
  'md.sys.opacity.disabled.outline': 'var(--md-sys-opacity-disabled-outline)',
  'md.sys.opacity.disabled.container': 'var(--md-sys-opacity-disabled-container)',
  'md.sys.typography.display-large.font-family': 'var(--md-sys-typography-display-large-font-family)',
  'md.sys.typography.display-medium.font-family': 'var(--md-sys-typography-display-medium-font-family)',
  'md.sys.typography.display-small.font-family': 'var(--md-sys-typography-display-small-font-family)',
  'md.sys.typography.headline-large.font-family': 'var(--md-sys-typography-headline-large-font-family)',
  'md.sys.typography.headline-medium.font-family': 'var(--md-sys-typography-headline-medium-font-family)',
  'md.sys.typography.headline-small.font-family': 'var(--md-sys-typography-headline-small-font-family)',
  'md.sys.typography.title-large.font-family': 'var(--md-sys-typography-title-large-font-family)',
  'md.sys.typography.title-medium.font-family': 'var(--md-sys-typography-title-medium-font-family)',
  'md.sys.typography.title-small.font-family': 'var(--md-sys-typography-title-small-font-family)',
  'md.sys.typography.body-large.font-family': 'var(--md-sys-typography-body-large-font-family)',
  'md.sys.typography.body-medium.font-family': 'var(--md-sys-typography-body-medium-font-family)',
  'md.sys.typography.body-small.font-family': 'var(--md-sys-typography-body-small-font-family)',
  'md.sys.typography.label-large.font-family': 'var(--md-sys-typography-label-large-font-family)',
  'md.sys.typography.label-medium.font-family': 'var(--md-sys-typography-label-medium-font-family)',
  'md.sys.typography.label-small.font-family': 'var(--md-sys-typography-label-small-font-family)',
  'md.sys.typography.display-large.font-weight': 'var(--md-sys-typography-display-large-font-weight)',
  'md.sys.typography.display-medium.font-weight': 'var(--md-sys-typography-display-medium-font-weight)',
  'md.sys.typography.display-small.font-weight': 'var(--md-sys-typography-display-small-font-weight)',
  'md.sys.typography.headline-large.font-weight': 'var(--md-sys-typography-headline-large-font-weight)',
  'md.sys.typography.headline-medium.font-weight': 'var(--md-sys-typography-headline-medium-font-weight)',
  'md.sys.typography.headline-small.font-weight': 'var(--md-sys-typography-headline-small-font-weight)',
  'md.sys.typography.title-large.font-weight': 'var(--md-sys-typography-title-large-font-weight)',
  'md.sys.typography.title-medium.font-weight': 'var(--md-sys-typography-title-medium-font-weight)',
  'md.sys.typography.title-small.font-weight': 'var(--md-sys-typography-title-small-font-weight)',
  'md.sys.typography.body-large.font-weight': 'var(--md-sys-typography-body-large-font-weight)',
  'md.sys.typography.body-medium.font-weight': 'var(--md-sys-typography-body-medium-font-weight)',
  'md.sys.typography.body-small.font-weight': 'var(--md-sys-typography-body-small-font-weight)',
  'md.sys.typography.label-large.font-weight': 'var(--md-sys-typography-label-large-font-weight)',
  'md.sys.typography.label-medium.font-weight': 'var(--md-sys-typography-label-medium-font-weight)',
  'md.sys.typography.label-small.font-weight': 'var(--md-sys-typography-label-small-font-weight)',
  'md.sys.typography.display-large.font-size': 'var(--md-sys-typography-display-large-font-size)',
  'md.sys.typography.display-medium.font-size': 'var(--md-sys-typography-display-medium-font-size)',
  'md.sys.typography.display-small.font-size': 'var(--md-sys-typography-display-small-font-size)',
  'md.sys.typography.headline-large.font-size': 'var(--md-sys-typography-headline-large-font-size)',
  'md.sys.typography.headline-medium.font-size': 'var(--md-sys-typography-headline-medium-font-size)',
  'md.sys.typography.headline-small.font-size': 'var(--md-sys-typography-headline-small-font-size)',
  'md.sys.typography.title-large.font-size': 'var(--md-sys-typography-title-large-font-size)',
  'md.sys.typography.title-medium.font-size': 'var(--md-sys-typography-title-medium-font-size)',
  'md.sys.typography.title-small.font-size': 'var(--md-sys-typography-title-small-font-size)',
  'md.sys.typography.body-large.font-size': 'var(--md-sys-typography-body-large-font-size)',
  'md.sys.typography.body-medium.font-size': 'var(--md-sys-typography-body-medium-font-size)',
  'md.sys.typography.body-small.font-size': 'var(--md-sys-typography-body-small-font-size)',
  'md.sys.typography.label-large.font-size': 'var(--md-sys-typography-label-large-font-size)',
  'md.sys.typography.label-medium.font-size': 'var(--md-sys-typography-label-medium-font-size)',
  'md.sys.typography.label-small.font-size': 'var(--md-sys-typography-label-small-font-size)',
  'md.sys.typography.display-large.line-height': 'var(--md-sys-typography-display-large-line-height)',
  'md.sys.typography.display-medium.line-height': 'var(--md-sys-typography-display-medium-line-height)',
  'md.sys.typography.display-small.line-height': 'var(--md-sys-typography-display-small-line-height)',
  'md.sys.typography.headline-large.line-height': 'var(--md-sys-typography-headline-large-line-height)',
  'md.sys.typography.headline-medium.line-height': 'var(--md-sys-typography-headline-medium-line-height)',
  'md.sys.typography.headline-small.line-height': 'var(--md-sys-typography-headline-small-line-height)',
  'md.sys.typography.title-large.line-height': 'var(--md-sys-typography-title-large-line-height)',
  'md.sys.typography.title-medium.line-height': 'var(--md-sys-typography-title-medium-line-height)',
  'md.sys.typography.title-small.line-height': 'var(--md-sys-typography-title-small-line-height)',
  'md.sys.typography.body-large.line-height': 'var(--md-sys-typography-body-large-line-height)',
  'md.sys.typography.body-medium.line-height': 'var(--md-sys-typography-body-medium-line-height)',
  'md.sys.typography.body-small.line-height': 'var(--md-sys-typography-body-small-line-height)',
  'md.sys.typography.label-large.line-height': 'var(--md-sys-typography-label-large-line-height)',
  'md.sys.typography.label-medium.line-height': 'var(--md-sys-typography-label-medium-line-height)',
  'md.sys.typography.label-small.line-height': 'var(--md-sys-typography-label-small-line-height)',
  'md.sys.typography.display-large.letter-spacing': 'var(--md-sys-typography-display-large-letter-spacing)',
  'md.sys.typography.display-medium.letter-spacing': 'var(--md-sys-typography-display-medium-letter-spacing)',
  'md.sys.typography.display-small.letter-spacing': 'var(--md-sys-typography-display-small-letter-spacing)',
  'md.sys.typography.headline-large.letter-spacing': 'var(--md-sys-typography-headline-large-letter-spacing)',
  'md.sys.typography.headline-medium.letter-spacing': 'var(--md-sys-typography-headline-medium-letter-spacing)',
  'md.sys.typography.headline-small.letter-spacing': 'var(--md-sys-typography-headline-small-letter-spacing)',
  'md.sys.typography.title-large.letter-spacing': 'var(--md-sys-typography-title-large-letter-spacing)',
  'md.sys.typography.title-medium.letter-spacing': 'var(--md-sys-typography-title-medium-letter-spacing)',
  'md.sys.typography.title-small.letter-spacing': 'var(--md-sys-typography-title-small-letter-spacing)',
  'md.sys.typography.body-large.letter-spacing': 'var(--md-sys-typography-body-large-letter-spacing)',
  'md.sys.typography.body-medium.letter-spacing': 'var(--md-sys-typography-body-medium-letter-spacing)',
  'md.sys.typography.body-small.letter-spacing': 'var(--md-sys-typography-body-small-letter-spacing)',
  'md.sys.typography.label-large.letter-spacing': 'var(--md-sys-typography-label-large-letter-spacing)',
  'md.sys.typography.label-medium.letter-spacing': 'var(--md-sys-typography-label-medium-letter-spacing)',
  'md.sys.typography.label-small.letter-spacing': 'var(--md-sys-typography-label-small-letter-spacing)',
  'md.sys.typography.display-large.font-style': 'var(--md-sys-typography-display-large-font-style)',
  'md.sys.typography.display-medium.font-style': 'var(--md-sys-typography-display-medium-font-style)',
  'md.sys.typography.display-small.font-style': 'var(--md-sys-typography-display-small-font-style)',
  'md.sys.typography.headline-large.font-style': 'var(--md-sys-typography-headline-large-font-style)',
  'md.sys.typography.headline-medium.font-style': 'var(--md-sys-typography-headline-medium-font-style)',
  'md.sys.typography.headline-small.font-style': 'var(--md-sys-typography-headline-small-font-style)',
  'md.sys.typography.title-large.font-style': 'var(--md-sys-typography-title-large-font-style)',
  'md.sys.typography.title-medium.font-style': 'var(--md-sys-typography-title-medium-font-style)',
  'md.sys.typography.title-small.font-style': 'var(--md-sys-typography-title-small-font-style)',
  'md.sys.typography.body-large.font-style': 'var(--md-sys-typography-body-large-font-style)',
  'md.sys.typography.body-medium.font-style': 'var(--md-sys-typography-body-medium-font-style)',
  'md.sys.typography.body-small.font-style': 'var(--md-sys-typography-body-small-font-style)',
  'md.sys.typography.label-large.font-style': 'var(--md-sys-typography-label-large-font-style)',
  'md.sys.typography.label-medium.font-style': 'var(--md-sys-typography-label-medium-font-style)',
  'md.sys.typography.label-small.font-style': 'var(--md-sys-typography-label-small-font-style)',
  'md.sys.typography.display-large.text-transform': 'var(--md-sys-typography-display-large-text-transform)',
  'md.sys.typography.display-medium.text-transform': 'var(--md-sys-typography-display-medium-text-transform)',
  'md.sys.typography.display-small.text-transform': 'var(--md-sys-typography-display-small-text-transform)',
  'md.sys.typography.headline-large.text-transform': 'var(--md-sys-typography-headline-large-text-transform)',
  'md.sys.typography.headline-medium.text-transform': 'var(--md-sys-typography-headline-medium-text-transform)',
  'md.sys.typography.headline-small.text-transform': 'var(--md-sys-typography-headline-small-text-transform)',
  'md.sys.typography.title-large.text-transform': 'var(--md-sys-typography-title-large-text-transform)',
  'md.sys.typography.title-medium.text-transform': 'var(--md-sys-typography-title-medium-text-transform)',
  'md.sys.typography.title-small.text-transform': 'var(--md-sys-typography-title-small-text-transform)',
  'md.sys.typography.body-large.text-transform': 'var(--md-sys-typography-body-large-text-transform)',
  'md.sys.typography.body-medium.text-transform': 'var(--md-sys-typography-body-medium-text-transform)',
  'md.sys.typography.body-small.text-transform': 'var(--md-sys-typography-body-small-text-transform)',
  'md.sys.typography.label-large.text-transform': 'var(--md-sys-typography-label-large-text-transform)',
  'md.sys.typography.label-medium.text-transform': 'var(--md-sys-typography-label-medium-text-transform)',
  'md.sys.typography.label-small.text-transform': 'var(--md-sys-typography-label-small-text-transform)',
  'md.sys.typography.display-large.text-decoration': 'var(--md-sys-typography-display-large-text-decoration)',
  'md.sys.typography.display-medium.text-decoration': 'var(--md-sys-typography-display-medium-text-decoration)',
  'md.sys.typography.display-small.text-decoration': 'var(--md-sys-typography-display-small-text-decoration)',
  'md.sys.typography.headline-large.text-decoration': 'var(--md-sys-typography-headline-large-text-decoration)',
  'md.sys.typography.headline-medium.text-decoration': 'var(--md-sys-typography-headline-medium-text-decoration)',
  'md.sys.typography.headline-small.text-decoration': 'var(--md-sys-typography-headline-small-text-decoration)',
  'md.sys.typography.title-large.text-decoration': 'var(--md-sys-typography-title-large-text-decoration)',
  'md.sys.typography.title-medium.text-decoration': 'var(--md-sys-typography-title-medium-text-decoration)',
  'md.sys.typography.title-small.text-decoration': 'var(--md-sys-typography-title-small-text-decoration)',
  'md.sys.typography.body-large.text-decoration': 'var(--md-sys-typography-body-large-text-decoration)',
  'md.sys.typography.body-medium.text-decoration': 'var(--md-sys-typography-body-medium-text-decoration)',
  'md.sys.typography.body-small.text-decoration': 'var(--md-sys-typography-body-small-text-decoration)',
  'md.sys.typography.label-large.text-decoration': 'var(--md-sys-typography-label-large-text-decoration)',
  'md.sys.typography.label-medium.text-decoration': 'var(--md-sys-typography-label-medium-text-decoration)',
  'md.sys.typography.label-small.text-decoration': 'var(--md-sys-typography-label-small-text-decoration)',
  'md.sys.color.background': 'var(--md-sys-color-background)',
  'md.sys.color.error-container': 'var(--md-sys-color-error-container)',
  'md.sys.color.error': 'var(--md-sys-color-error)',
  'md.sys.color.inverse-on-surface': 'var(--md-sys-color-inverse-on-surface)',
  'md.sys.color.inverse-primary': 'var(--md-sys-color-inverse-primary)',
  'md.sys.color.inverse-surface': 'var(--md-sys-color-inverse-surface)',
  'md.sys.color.on-background': 'var(--md-sys-color-on-background)',
  'md.sys.color.on-error-container': 'var(--md-sys-color-on-error-container)',
  'md.sys.color.on-error': 'var(--md-sys-color-on-error)',
  'md.sys.color.on-primary-container': 'var(--md-sys-color-on-primary-container)',
  'md.sys.color.on-primary-fixed-variant': 'var(--md-sys-color-on-primary-fixed-variant)',
  'md.sys.color.on-primary-fixed': 'var(--md-sys-color-on-primary-fixed)',
  'md.sys.color.on-primary': 'var(--md-sys-color-on-primary)',
  'md.sys.color.on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
  'md.sys.color.on-secondary-fixed-variant': 'var(--md-sys-color-on-secondary-fixed-variant)',
  'md.sys.color.on-secondary-fixed': 'var(--md-sys-color-on-secondary-fixed)',
  'md.sys.color.on-secondary': 'var(--md-sys-color-on-secondary)',
  'md.sys.color.on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
  'md.sys.color.on-surface': 'var(--md-sys-color-on-surface)',
  'md.sys.color.on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
  'md.sys.color.on-tertiary-fixed-variant': 'var(--md-sys-color-on-tertiary-fixed-variant)',
  'md.sys.color.on-tertiary-fixed': 'var(--md-sys-color-on-tertiary-fixed)',
  'md.sys.color.on-tertiary': 'var(--md-sys-color-on-tertiary)',
  'md.sys.color.outline-variant': 'var(--md-sys-color-outline-variant)',
  'md.sys.color.outline': 'var(--md-sys-color-outline)',
  'md.sys.color.primary-container': 'var(--md-sys-color-primary-container)',
  'md.sys.color.primary-fixed-dim': 'var(--md-sys-color-primary-fixed-dim)',
  'md.sys.color.primary-fixed': 'var(--md-sys-color-primary-fixed)',
  'md.sys.color.primary': 'var(--md-sys-color-primary)',
  'md.sys.color.scrim': 'var(--md-sys-color-scrim)',
  'md.sys.color.secondary-container': 'var(--md-sys-color-secondary-container)',
  'md.sys.color.secondary-fixed-dim': 'var(--md-sys-color-secondary-fixed-dim)',
  'md.sys.color.secondary-fixed': 'var(--md-sys-color-secondary-fixed)',
  'md.sys.color.secondary': 'var(--md-sys-color-secondary)',
  'md.sys.color.shadow': 'var(--md-sys-color-shadow)',
  'md.sys.color.surface-bright': 'var(--md-sys-color-surface-bright)',
  'md.sys.color.surface-container-high': 'var(--md-sys-color-surface-container-high)',
  'md.sys.color.surface-container-highest': 'var(--md-sys-color-surface-container-highest)',
  'md.sys.color.surface-container-low': 'var(--md-sys-color-surface-container-low)',
  'md.sys.color.surface-container-lowest': 'var(--md-sys-color-surface-container-lowest)',
  'md.sys.color.surface-container': 'var(--md-sys-color-surface-container)',
  'md.sys.color.surface-dim': 'var(--md-sys-color-surface-dim)',
  'md.sys.color.surface-tint': 'var(--md-sys-color-surface-tint)',
  'md.sys.color.surface-variant': 'var(--md-sys-color-surface-variant)',
  'md.sys.color.surface': 'var(--md-sys-color-surface)',
  'md.sys.color.tertiary-container': 'var(--md-sys-color-tertiary-container)',
  'md.sys.color.tertiary-fixed-dim': 'var(--md-sys-color-tertiary-fixed-dim)',
  'md.sys.color.tertiary-fixed': 'var(--md-sys-color-tertiary-fixed)',
  'md.sys.color.tertiary': 'var(--md-sys-color-tertiary)',
} as const;
