import * as stylex from '@stylexjs/stylex';
import { expressiveSysColor, expressiveSysCrsv, expressiveSysDuration, expressiveSysFill, expressiveSysFontFamily, expressiveSysFontSize, expressiveSysFontStyle, expressiveSysFontWeight, expressiveSysGrad, expressiveSysHexp, expressiveSysLetterSpacing, expressiveSysLineHeight, expressiveSysOpacity, expressiveSysOpsz, expressiveSysRond, expressiveSysSlnt, expressiveSysTextDecoration, expressiveSysTextTransform, expressiveSysTimingFunction, expressiveSysWdth, expressiveSysWght } from './sys.stylex';

export const expressivePresetReset = stylex.create({
  button: {
    borderBottomStyle: 'none',
    borderLeftStyle: 'none',
    borderRightStyle: 'none',
    borderTopStyle: 'none',
    outlineStyle: 'none',
    paddingBottom: '0px',
    paddingLeft: '0px',
    paddingRight: '0px',
    paddingTop: '0px',
  },
  anchor: {
    color: 'inherit',
    textDecorationLine: 'none',
  },
});

export const expressivePresetPrepare = stylex.create({
  border: {
    borderBottomColor: `rgb(${expressiveSysColor.outline})`,
    borderBottomStyle: 'solid',
    borderLeftColor: `rgb(${expressiveSysColor.outline})`,
    borderLeftStyle: 'solid',
    borderRightColor: `rgb(${expressiveSysColor.outline})`,
    borderRightStyle: 'solid',
    borderTopColor: `rgb(${expressiveSysColor.outline})`,
    borderTopStyle: 'solid',
  },
});

export const expressivePresetDisabled = stylex.create({
  content: {
    color: `rgb(${expressiveSysColor.onSurfaceVariant}/${expressiveSysOpacity.disabledContent})`,
  },
  container: {
    backgroundColor: `rgb(${expressiveSysColor.onSurfaceVariant}/${expressiveSysOpacity.disabledContainer})`,
  },
  outline: {
    borderBottomColor: `rgb(${expressiveSysColor.onSurfaceVariant}/${expressiveSysOpacity.disabledOutline})`,
    borderLeftColor: `rgb(${expressiveSysColor.onSurfaceVariant}/${expressiveSysOpacity.disabledOutline})`,
    borderRightColor: `rgb(${expressiveSysColor.onSurfaceVariant}/${expressiveSysOpacity.disabledOutline})`,
    borderTopColor: `rgb(${expressiveSysColor.onSurfaceVariant}/${expressiveSysOpacity.disabledOutline})`,
  },
});

export const expressivePresetFont = stylex.create({
  displayLarge: {
    fontFamily: expressiveSysFontFamily.displayLarge,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.displayLarge}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.displayLarge,
    fontVariationSettings: `'wght' ${expressiveSysWght.displayLarge}, 'grad' ${expressiveSysGrad.displayLarge}, 'wdth' ${expressiveSysWdth.displayLarge}, 'rond' ${expressiveSysRond.displayLarge}, 'opsz' ${expressiveSysOpsz.displayLarge}, 'crsv' ${expressiveSysCrsv.displayLarge}, 'slnt' ${expressiveSysSlnt.displayLarge}, 'fill' ${expressiveSysFill.displayLarge}, 'hexp' ${expressiveSysHexp.displayLarge}`,
    fontWeight: expressiveSysFontWeight.displayLarge,
    letterSpacing: `calc(${expressiveSysLetterSpacing.displayLarge}/${expressiveSysFontSize.displayLarge}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.displayLarge}/${expressiveSysFontSize.displayLarge})`,
    textDecoration: expressiveSysTextDecoration.displayLarge,
    textTransform: expressiveSysTextTransform.displayLarge,
  },
  displayMedium: {
    fontFamily: expressiveSysFontFamily.displayMedium,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.displayMedium}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.displayMedium,
    fontVariationSettings: `'wght' ${expressiveSysWght.displayMedium}, 'grad' ${expressiveSysGrad.displayMedium}, 'wdth' ${expressiveSysWdth.displayMedium}, 'rond' ${expressiveSysRond.displayMedium}, 'opsz' ${expressiveSysOpsz.displayMedium}, 'crsv' ${expressiveSysCrsv.displayMedium}, 'slnt' ${expressiveSysSlnt.displayMedium}, 'fill' ${expressiveSysFill.displayMedium}, 'hexp' ${expressiveSysHexp.displayMedium}`,
    fontWeight: expressiveSysFontWeight.displayMedium,
    letterSpacing: `calc(${expressiveSysLetterSpacing.displayMedium}/${expressiveSysFontSize.displayMedium}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.displayMedium}/${expressiveSysFontSize.displayMedium})`,
    textDecoration: expressiveSysTextDecoration.displayMedium,
    textTransform: expressiveSysTextTransform.displayMedium,
  },
  displaySmall: {
    fontFamily: expressiveSysFontFamily.displaySmall,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.displaySmall}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.displaySmall,
    fontVariationSettings: `'wght' ${expressiveSysWght.displaySmall}, 'grad' ${expressiveSysGrad.displaySmall}, 'wdth' ${expressiveSysWdth.displaySmall}, 'rond' ${expressiveSysRond.displaySmall}, 'opsz' ${expressiveSysOpsz.displaySmall}, 'crsv' ${expressiveSysCrsv.displaySmall}, 'slnt' ${expressiveSysSlnt.displaySmall}, 'fill' ${expressiveSysFill.displaySmall}, 'hexp' ${expressiveSysHexp.displaySmall}`,
    fontWeight: expressiveSysFontWeight.displaySmall,
    letterSpacing: `calc(${expressiveSysLetterSpacing.displaySmall}/${expressiveSysFontSize.displaySmall}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.displaySmall}/${expressiveSysFontSize.displaySmall})`,
    textDecoration: expressiveSysTextDecoration.displaySmall,
    textTransform: expressiveSysTextTransform.displaySmall,
  },
  headlineLarge: {
    fontFamily: expressiveSysFontFamily.headlineLarge,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.headlineLarge}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.headlineLarge,
    fontVariationSettings: `'wght' ${expressiveSysWght.headlineLarge}, 'grad' ${expressiveSysGrad.headlineLarge}, 'wdth' ${expressiveSysWdth.headlineLarge}, 'rond' ${expressiveSysRond.headlineLarge}, 'opsz' ${expressiveSysOpsz.headlineLarge}, 'crsv' ${expressiveSysCrsv.headlineLarge}, 'slnt' ${expressiveSysSlnt.headlineLarge}, 'fill' ${expressiveSysFill.headlineLarge}, 'hexp' ${expressiveSysHexp.headlineLarge}`,
    fontWeight: expressiveSysFontWeight.headlineLarge,
    letterSpacing: `calc(${expressiveSysLetterSpacing.headlineLarge}/${expressiveSysFontSize.headlineLarge}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.headlineLarge}/${expressiveSysFontSize.headlineLarge})`,
    textDecoration: expressiveSysTextDecoration.headlineLarge,
    textTransform: expressiveSysTextTransform.headlineLarge,
  },
  headlineMedium: {
    fontFamily: expressiveSysFontFamily.headlineMedium,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.headlineMedium}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.headlineMedium,
    fontVariationSettings: `'wght' ${expressiveSysWght.headlineMedium}, 'grad' ${expressiveSysGrad.headlineMedium}, 'wdth' ${expressiveSysWdth.headlineMedium}, 'rond' ${expressiveSysRond.headlineMedium}, 'opsz' ${expressiveSysOpsz.headlineMedium}, 'crsv' ${expressiveSysCrsv.headlineMedium}, 'slnt' ${expressiveSysSlnt.headlineMedium}, 'fill' ${expressiveSysFill.headlineMedium}, 'hexp' ${expressiveSysHexp.headlineMedium}`,
    fontWeight: expressiveSysFontWeight.headlineMedium,
    letterSpacing: `calc(${expressiveSysLetterSpacing.headlineMedium}/${expressiveSysFontSize.headlineMedium}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.headlineMedium}/${expressiveSysFontSize.headlineMedium})`,
    textDecoration: expressiveSysTextDecoration.headlineMedium,
    textTransform: expressiveSysTextTransform.headlineMedium,
  },
  headlineSmall: {
    fontFamily: expressiveSysFontFamily.headlineSmall,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.headlineSmall}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.headlineSmall,
    fontVariationSettings: `'wght' ${expressiveSysWght.headlineSmall}, 'grad' ${expressiveSysGrad.headlineSmall}, 'wdth' ${expressiveSysWdth.headlineSmall}, 'rond' ${expressiveSysRond.headlineSmall}, 'opsz' ${expressiveSysOpsz.headlineSmall}, 'crsv' ${expressiveSysCrsv.headlineSmall}, 'slnt' ${expressiveSysSlnt.headlineSmall}, 'fill' ${expressiveSysFill.headlineSmall}, 'hexp' ${expressiveSysHexp.headlineSmall}`,
    fontWeight: expressiveSysFontWeight.headlineSmall,
    letterSpacing: `calc(${expressiveSysLetterSpacing.headlineSmall}/${expressiveSysFontSize.headlineSmall}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.headlineSmall}/${expressiveSysFontSize.headlineSmall})`,
    textDecoration: expressiveSysTextDecoration.headlineSmall,
    textTransform: expressiveSysTextTransform.headlineSmall,
  },
  bodyLarge: {
    fontFamily: expressiveSysFontFamily.bodyLarge,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.bodyLarge}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.bodyLarge,
    fontVariationSettings: `'wght' ${expressiveSysWght.bodyLarge}, 'grad' ${expressiveSysGrad.bodyLarge}, 'wdth' ${expressiveSysWdth.bodyLarge}, 'rond' ${expressiveSysRond.bodyLarge}, 'opsz' ${expressiveSysOpsz.bodyLarge}, 'crsv' ${expressiveSysCrsv.bodyLarge}, 'slnt' ${expressiveSysSlnt.bodyLarge}, 'fill' ${expressiveSysFill.bodyLarge}, 'hexp' ${expressiveSysHexp.bodyLarge}`,
    fontWeight: expressiveSysFontWeight.bodyLarge,
    letterSpacing: `calc(${expressiveSysLetterSpacing.bodyLarge}/${expressiveSysFontSize.bodyLarge}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.bodyLarge}/${expressiveSysFontSize.bodyLarge})`,
    textDecoration: expressiveSysTextDecoration.bodyLarge,
    textTransform: expressiveSysTextTransform.bodyLarge,
  },
  bodyMedium: {
    fontFamily: expressiveSysFontFamily.bodyMedium,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.bodyMedium}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.bodyMedium,
    fontVariationSettings: `'wght' ${expressiveSysWght.bodyMedium}, 'grad' ${expressiveSysGrad.bodyMedium}, 'wdth' ${expressiveSysWdth.bodyMedium}, 'rond' ${expressiveSysRond.bodyMedium}, 'opsz' ${expressiveSysOpsz.bodyMedium}, 'crsv' ${expressiveSysCrsv.bodyMedium}, 'slnt' ${expressiveSysSlnt.bodyMedium}, 'fill' ${expressiveSysFill.bodyMedium}, 'hexp' ${expressiveSysHexp.bodyMedium}`,
    fontWeight: expressiveSysFontWeight.bodyMedium,
    letterSpacing: `calc(${expressiveSysLetterSpacing.bodyMedium}/${expressiveSysFontSize.bodyMedium}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.bodyMedium}/${expressiveSysFontSize.bodyMedium})`,
    textDecoration: expressiveSysTextDecoration.bodyMedium,
    textTransform: expressiveSysTextTransform.bodyMedium,
  },
  bodySmall: {
    fontFamily: expressiveSysFontFamily.bodySmall,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.bodySmall}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.bodySmall,
    fontVariationSettings: `'wght' ${expressiveSysWght.bodySmall}, 'grad' ${expressiveSysGrad.bodySmall}, 'wdth' ${expressiveSysWdth.bodySmall}, 'rond' ${expressiveSysRond.bodySmall}, 'opsz' ${expressiveSysOpsz.bodySmall}, 'crsv' ${expressiveSysCrsv.bodySmall}, 'slnt' ${expressiveSysSlnt.bodySmall}, 'fill' ${expressiveSysFill.bodySmall}, 'hexp' ${expressiveSysHexp.bodySmall}`,
    fontWeight: expressiveSysFontWeight.bodySmall,
    letterSpacing: `calc(${expressiveSysLetterSpacing.bodySmall}/${expressiveSysFontSize.bodySmall}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.bodySmall}/${expressiveSysFontSize.bodySmall})`,
    textDecoration: expressiveSysTextDecoration.bodySmall,
    textTransform: expressiveSysTextTransform.bodySmall,
  },
  titleLarge: {
    fontFamily: expressiveSysFontFamily.titleLarge,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.titleLarge}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.titleLarge,
    fontVariationSettings: `'wght' ${expressiveSysWght.titleLarge}, 'grad' ${expressiveSysGrad.titleLarge}, 'wdth' ${expressiveSysWdth.titleLarge}, 'rond' ${expressiveSysRond.titleLarge}, 'opsz' ${expressiveSysOpsz.titleLarge}, 'crsv' ${expressiveSysCrsv.titleLarge}, 'slnt' ${expressiveSysSlnt.titleLarge}, 'fill' ${expressiveSysFill.titleLarge}, 'hexp' ${expressiveSysHexp.titleLarge}`,
    fontWeight: expressiveSysFontWeight.titleLarge,
    letterSpacing: `calc(${expressiveSysLetterSpacing.titleLarge}/${expressiveSysFontSize.titleLarge}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.titleLarge}/${expressiveSysFontSize.titleLarge})`,
    textDecoration: expressiveSysTextDecoration.titleLarge,
    textTransform: expressiveSysTextTransform.titleLarge,
  },
  titleMedium: {
    fontFamily: expressiveSysFontFamily.titleMedium,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.titleMedium}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.titleMedium,
    fontVariationSettings: `'wght' ${expressiveSysWght.titleMedium}, 'grad' ${expressiveSysGrad.titleMedium}, 'wdth' ${expressiveSysWdth.titleMedium}, 'rond' ${expressiveSysRond.titleMedium}, 'opsz' ${expressiveSysOpsz.titleMedium}, 'crsv' ${expressiveSysCrsv.titleMedium}, 'slnt' ${expressiveSysSlnt.titleMedium}, 'fill' ${expressiveSysFill.titleMedium}, 'hexp' ${expressiveSysHexp.titleMedium}`,
    fontWeight: expressiveSysFontWeight.titleMedium,
    letterSpacing: `calc(${expressiveSysLetterSpacing.titleMedium}/${expressiveSysFontSize.titleMedium}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.titleMedium}/${expressiveSysFontSize.titleMedium})`,
    textDecoration: expressiveSysTextDecoration.titleMedium,
    textTransform: expressiveSysTextTransform.titleMedium,
  },
  titleSmall: {
    fontFamily: expressiveSysFontFamily.titleSmall,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.titleSmall}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.titleSmall,
    fontVariationSettings: `'wght' ${expressiveSysWght.titleSmall}, 'grad' ${expressiveSysGrad.titleSmall}, 'wdth' ${expressiveSysWdth.titleSmall}, 'rond' ${expressiveSysRond.titleSmall}, 'opsz' ${expressiveSysOpsz.titleSmall}, 'crsv' ${expressiveSysCrsv.titleSmall}, 'slnt' ${expressiveSysSlnt.titleSmall}, 'fill' ${expressiveSysFill.titleSmall}, 'hexp' ${expressiveSysHexp.titleSmall}`,
    fontWeight: expressiveSysFontWeight.titleSmall,
    letterSpacing: `calc(${expressiveSysLetterSpacing.titleSmall}/${expressiveSysFontSize.titleSmall}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.titleSmall}/${expressiveSysFontSize.titleSmall})`,
    textDecoration: expressiveSysTextDecoration.titleSmall,
    textTransform: expressiveSysTextTransform.titleSmall,
  },
  labelLarge: {
    fontFamily: expressiveSysFontFamily.labelLarge,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.labelLarge}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.labelLarge,
    fontVariationSettings: `'wght' ${expressiveSysWght.labelLarge}, 'grad' ${expressiveSysGrad.labelLarge}, 'wdth' ${expressiveSysWdth.labelLarge}, 'rond' ${expressiveSysRond.labelLarge}, 'opsz' ${expressiveSysOpsz.labelLarge}, 'crsv' ${expressiveSysCrsv.labelLarge}, 'slnt' ${expressiveSysSlnt.labelLarge}, 'fill' ${expressiveSysFill.labelLarge}, 'hexp' ${expressiveSysHexp.labelLarge}`,
    fontWeight: expressiveSysFontWeight.labelLarge,
    letterSpacing: `calc(${expressiveSysLetterSpacing.labelLarge}/${expressiveSysFontSize.labelLarge}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.labelLarge}/${expressiveSysFontSize.labelLarge})`,
    textDecoration: expressiveSysTextDecoration.labelLarge,
    textTransform: expressiveSysTextTransform.labelLarge,
  },
  labelMedium: {
    fontFamily: expressiveSysFontFamily.labelMedium,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.labelMedium}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.labelMedium,
    fontVariationSettings: `'wght' ${expressiveSysWght.labelMedium}, 'grad' ${expressiveSysGrad.labelMedium}, 'wdth' ${expressiveSysWdth.labelMedium}, 'rond' ${expressiveSysRond.labelMedium}, 'opsz' ${expressiveSysOpsz.labelMedium}, 'crsv' ${expressiveSysCrsv.labelMedium}, 'slnt' ${expressiveSysSlnt.labelMedium}, 'fill' ${expressiveSysFill.labelMedium}, 'hexp' ${expressiveSysHexp.labelMedium}`,
    fontWeight: expressiveSysFontWeight.labelMedium,
    letterSpacing: `calc(${expressiveSysLetterSpacing.labelMedium}/${expressiveSysFontSize.labelMedium}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.labelMedium}/${expressiveSysFontSize.labelMedium})`,
    textDecoration: expressiveSysTextDecoration.labelMedium,
    textTransform: expressiveSysTextTransform.labelMedium,
  },
  labelSmall: {
    fontFamily: expressiveSysFontFamily.labelSmall,
    fontOpticalSizing: 'auto',
    fontSize: `calc(${expressiveSysFontSize.labelSmall}/16*1rem)`,
    fontStyle: expressiveSysFontStyle.labelSmall,
    fontVariationSettings: `'wght' ${expressiveSysWght.labelSmall}, 'grad' ${expressiveSysGrad.labelSmall}, 'wdth' ${expressiveSysWdth.labelSmall}, 'rond' ${expressiveSysRond.labelSmall}, 'opsz' ${expressiveSysOpsz.labelSmall}, 'crsv' ${expressiveSysCrsv.labelSmall}, 'slnt' ${expressiveSysSlnt.labelSmall}, 'fill' ${expressiveSysFill.labelSmall}, 'hexp' ${expressiveSysHexp.labelSmall}`,
    fontWeight: expressiveSysFontWeight.labelSmall,
    letterSpacing: `calc(${expressiveSysLetterSpacing.labelSmall}/${expressiveSysFontSize.labelSmall}*1em)`,
    lineHeight: `calc(${expressiveSysLineHeight.labelSmall}/${expressiveSysFontSize.labelSmall})`,
    textDecoration: expressiveSysTextDecoration.labelSmall,
    textTransform: expressiveSysTextTransform.labelSmall,
  },
});

export const expressivePresetTransition = stylex.create({
  spatialFast: {
    transitionDuration: expressiveSysDuration.spatialFast,
    transitionTimingFunction: expressiveSysTimingFunction.spatialFast,
  },
  spatialDefault: {
    transitionDuration: expressiveSysDuration.spatialDefault,
    transitionTimingFunction: expressiveSysTimingFunction.spatialDefault,
  },
  spatialSlow: {
    transitionDuration: expressiveSysDuration.spatialSlow,
    transitionTimingFunction: expressiveSysTimingFunction.spatialSlow,
  },
  effectsFast: {
    transitionDuration: expressiveSysDuration.effectsFast,
    transitionTimingFunction: expressiveSysTimingFunction.effectsFast,
  },
  effectsDefault: {
    transitionDuration: expressiveSysDuration.effectsDefault,
    transitionTimingFunction: expressiveSysTimingFunction.effectsDefault,
  },
  effectsSlow: {
    transitionDuration: expressiveSysDuration.effectsSlow,
    transitionTimingFunction: expressiveSysTimingFunction.effectsSlow,
  },
});
