import * as stylex from '@stylexjs/stylex';
import { expressivePaletteDefault } from './palette.stylex';
import { expressiveRefFontFamily } from './ref.stylex';

export const expressiveSysColor = stylex.defineVars({
  background: expressivePaletteDefault.background,
  error: expressivePaletteDefault.error,
  errorContainer: expressivePaletteDefault.errorContainer,
  inverseOnSurface: expressivePaletteDefault.inverseOnSurface,
  inversePrimary: expressivePaletteDefault.inversePrimary,
  inverseSurface: expressivePaletteDefault.inverseSurface,
  onBackground: expressivePaletteDefault.onBackground,
  onError: expressivePaletteDefault.onError,
  onErrorContainer: expressivePaletteDefault.onErrorContainer,
  onPrimary: expressivePaletteDefault.onPrimary,
  onPrimaryContainer: expressivePaletteDefault.onPrimaryContainer,
  onPrimaryFixed: expressivePaletteDefault.onPrimaryFixed,
  onPrimaryFixedVariant: expressivePaletteDefault.onPrimaryFixedVariant,
  onSecondary: expressivePaletteDefault.onSecondary,
  onSecondaryContainer: expressivePaletteDefault.onSecondaryContainer,
  onSecondaryFixed: expressivePaletteDefault.onSecondaryFixed,
  onSecondaryFixedVariant: expressivePaletteDefault.onSecondaryFixedVariant,
  onSurface: expressivePaletteDefault.onSurface,
  onSurfaceVariant: expressivePaletteDefault.onSurfaceVariant,
  onTertiary: expressivePaletteDefault.onTertiary,
  onTertiaryContainer: expressivePaletteDefault.onTertiaryContainer,
  onTertiaryFixed: expressivePaletteDefault.onTertiaryFixed,
  onTertiaryFixedVariant: expressivePaletteDefault.onTertiaryFixedVariant,
  outline: expressivePaletteDefault.outline,
  outlineVariant: expressivePaletteDefault.outlineVariant,
  primary: expressivePaletteDefault.primary,
  primaryContainer: expressivePaletteDefault.primaryContainer,
  primaryFixed: expressivePaletteDefault.primaryFixed,
  primaryFixedDim: expressivePaletteDefault.primaryFixedDim,
  scrim: expressivePaletteDefault.scrim,
  secondary: expressivePaletteDefault.secondary,
  secondaryContainer: expressivePaletteDefault.secondaryContainer,
  secondaryFixed: expressivePaletteDefault.secondaryFixed,
  secondaryFixedDim: expressivePaletteDefault.secondaryFixedDim,
  shadow: expressivePaletteDefault.shadow,
  surface: expressivePaletteDefault.surface,
  surfaceBright: expressivePaletteDefault.surfaceBright,
  surfaceContainer: expressivePaletteDefault.surfaceContainer,
  surfaceContainerHigh: expressivePaletteDefault.surfaceContainerHigh,
  surfaceContainerHighest: expressivePaletteDefault.surfaceContainerHighest,
  surfaceContainerLow: expressivePaletteDefault.surfaceContainerLow,
  surfaceContainerLowest: expressivePaletteDefault.surfaceContainerLowest,
  surfaceDim: expressivePaletteDefault.surfaceDim,
  surfaceTint: expressivePaletteDefault.surfaceTint,
  surfaceVariant: expressivePaletteDefault.surfaceVariant,
  tertiary: expressivePaletteDefault.tertiary,
  tertiaryContainer: expressivePaletteDefault.tertiaryContainer,
  tertiaryFixed: expressivePaletteDefault.tertiaryFixed,
  tertiaryFixedDim: expressivePaletteDefault.tertiaryFixedDim,
});

export const expressiveSysRadius = stylex.defineVars({
  full: stylex.types.length(9999),
  extraExtraLarge: stylex.types.length(48),
  extraLargeIncreased: stylex.types.length(32),
  extraLarge: stylex.types.length(28),
  largeIncreased: stylex.types.length(20),
  large: stylex.types.length(16),
  medium: stylex.types.length(12),
  small: stylex.types.length(8),
  extraSmall: stylex.types.length(4),
  none: stylex.types.length(0),
});

export const expressiveSysTimingFunction = stylex.defineVars({
  spatialFast: 'cubic-bezier(0.42, 1.67, 0.21, 0.90)',
  spatialDefault: 'cubic-bezier(0.38, 1.21, 0.22, 1.00)',
  spatialSlow: 'cubic-bezier(0.39, 1.29, 0.35, 0.98)',

  effectsFast: 'cubic-bezier(0.31, 0.94, 0.34, 1.00)',
  effectsDefault: 'cubic-bezier(0.34, 0.80, 0.34, 1.00)',
  effectsSlow: 'cubic-bezier(0.34, 0.88, 0.34, 1.00)',
});

export const expressiveSysDuration = stylex.defineVars({
  spatialFast: stylex.types.time('350ms'),
  spatialDefault: stylex.types.time('500ms'),
  spatialSlow: stylex.types.time('650ms'),

  effectsFast: stylex.types.time('150ms'),
  effectsDefault: stylex.types.time('200ms'),
  effectsSlow: stylex.types.time('300ms'),
});

export const expressiveSysOpacity = stylex.defineVars({
  pressed: stylex.types.number(0.12),
  focused: stylex.types.number(0.12),
  hovered: stylex.types.number(0.08),
  dragged: stylex.types.number(0.16),

  scrim: stylex.types.number(0.32),

  shadow: stylex.types.number(0.4),

  disabledContent: stylex.types.number(0.38),
  disabledOutline: stylex.types.number(0.38),
  disabledContainer: stylex.types.number(0.12),
});

export const expressiveSysFontFamily = stylex.defineVars({
  displayLarge: expressiveRefFontFamily.sans,
  displayMedium: expressiveRefFontFamily.sans,
  displaySmall: expressiveRefFontFamily.sans,
  headlineLarge: expressiveRefFontFamily.sans,
  headlineMedium: expressiveRefFontFamily.sans,
  headlineSmall: expressiveRefFontFamily.sans,
  titleLarge: expressiveRefFontFamily.sans,
  titleMedium: expressiveRefFontFamily.sans,
  titleSmall: expressiveRefFontFamily.sans,
  bodyLarge: expressiveRefFontFamily.sans,
  bodyMedium: expressiveRefFontFamily.sans,
  bodySmall: expressiveRefFontFamily.sans,
  labelLarge: expressiveRefFontFamily.sans,
  labelMedium: expressiveRefFontFamily.sans,
  labelSmall: expressiveRefFontFamily.sans,
});

export const expressiveSysFontWeight = stylex.defineVars({
  displayLarge: stylex.types.integer(500),
  displayMedium: stylex.types.integer(500),
  displaySmall: stylex.types.integer(500),
  headlineLarge: stylex.types.integer(500),
  headlineMedium: stylex.types.integer(500),
  headlineSmall: stylex.types.integer(500),
  titleLarge: stylex.types.integer(500),
  titleMedium: stylex.types.integer(700),
  titleSmall: stylex.types.integer(700),
  bodyLarge: stylex.types.integer(500),
  bodyMedium: stylex.types.integer(500),
  bodySmall: stylex.types.integer(500),
  labelLarge: stylex.types.integer(700),
  labelMedium: stylex.types.integer(700),
  labelSmall: stylex.types.integer(700),
});

export const expressiveSysFontSize = stylex.defineVars({
  displayLarge: stylex.types.integer(57),
  displayMedium: stylex.types.integer(45),
  displaySmall: stylex.types.integer(36),
  headlineLarge: stylex.types.integer(32),
  headlineMedium: stylex.types.integer(28),
  headlineSmall: stylex.types.integer(24),
  titleLarge: stylex.types.integer(22),
  titleMedium: stylex.types.integer(16),
  titleSmall: stylex.types.integer(14),
  bodyLarge: stylex.types.integer(16),
  bodyMedium: stylex.types.integer(14),
  bodySmall: stylex.types.integer(12),
  labelLarge: stylex.types.integer(14),
  labelMedium: stylex.types.integer(12),
  labelSmall: stylex.types.integer(11),
});

export const expressiveSysLineHeight = stylex.defineVars({
  displayLarge: stylex.types.integer(64),
  displayMedium: stylex.types.integer(52),
  displaySmall: stylex.types.integer(44),
  headlineLarge: stylex.types.integer(40),
  headlineMedium: stylex.types.integer(36),
  headlineSmall: stylex.types.integer(32),
  titleLarge: stylex.types.integer(28),
  titleMedium: stylex.types.integer(24),
  titleSmall: stylex.types.integer(20),
  bodyLarge: stylex.types.integer(24),
  bodyMedium: stylex.types.integer(20),
  bodySmall: stylex.types.integer(16),
  labelLarge: stylex.types.integer(20),
  labelMedium: stylex.types.integer(16),
  labelSmall: stylex.types.integer(16),
});

export const expressiveSysLetterSpacing = stylex.defineVars({
  displayLarge: stylex.types.number(-0.25),
  displayMedium: stylex.types.number(0),
  displaySmall: stylex.types.number(0),
  headlineLarge: stylex.types.number(0),
  headlineMedium: stylex.types.number(0),
  headlineSmall: stylex.types.number(0),
  titleLarge: stylex.types.number(0),
  titleMedium: stylex.types.number(0.15),
  titleSmall: stylex.types.number(0.1),
  bodyLarge: stylex.types.number(0.5),
  bodyMedium: stylex.types.number(0.25),
  bodySmall: stylex.types.number(0.4),
  labelLarge: stylex.types.number(0.1),
  labelMedium: stylex.types.number(0.5),
  labelSmall: stylex.types.number(0.5),
});

export const expressiveSysFontStyle = stylex.defineVars({
  displayLarge: 'normal',
  displayMedium: 'normal',
  displaySmall: 'normal',
  headlineLarge: 'normal',
  headlineMedium: 'normal',
  headlineSmall: 'normal',
  titleLarge: 'normal',
  titleMedium: 'normal',
  titleSmall: 'normal',
  bodyLarge: 'normal',
  bodyMedium: 'normal',
  bodySmall: 'normal',
  labelLarge: 'normal',
  labelMedium: 'normal',
  labelSmall: 'normal',
});

export const expressiveSysTextTransform = stylex.defineVars({
  displayLarge: 'none',
  displayMedium: 'none',
  displaySmall: 'none',
  headlineLarge: 'none',
  headlineMedium: 'none',
  headlineSmall: 'none',
  titleLarge: 'none',
  titleMedium: 'none',
  titleSmall: 'none',
  bodyLarge: 'none',
  bodyMedium: 'none',
  bodySmall: 'none',
  labelLarge: 'none',
  labelMedium: 'none',
  labelSmall: 'none',
});

export const expressiveSysTextDecoration = stylex.defineVars({
  displayLarge: 'none',
  displayMedium: 'none',
  displaySmall: 'none',
  headlineLarge: 'none',
  headlineMedium: 'none',
  headlineSmall: 'none',
  titleLarge: 'none',
  titleMedium: 'none',
  titleSmall: 'none',
  bodyLarge: 'none',
  bodyMedium: 'none',
  bodySmall: 'none',
  labelLarge: 'none',
  labelMedium: 'none',
  labelSmall: 'none',
});

export const expressiveSysWght = stylex.defineVars({
  displayLarge: stylex.types.integer(500),
  displayMedium: stylex.types.integer(500),
  displaySmall: stylex.types.integer(500),
  headlineLarge: stylex.types.integer(500),
  headlineMedium: stylex.types.integer(500),
  headlineSmall: stylex.types.integer(500),
  titleLarge: stylex.types.integer(500),
  titleMedium: stylex.types.integer(600),
  titleSmall: stylex.types.integer(600),
  bodyLarge: stylex.types.integer(500),
  bodyMedium: stylex.types.integer(500),
  bodySmall: stylex.types.integer(500),
  labelLarge: stylex.types.integer(600),
  labelMedium: stylex.types.integer(600),
  labelSmall: stylex.types.integer(600),
});

export const expressiveSysOpsz = stylex.defineVars({
  displayLarge: stylex.types.integer(57),
  displayMedium: stylex.types.integer(45),
  displaySmall: stylex.types.integer(36),
  headlineLarge: stylex.types.integer(32),
  headlineMedium: stylex.types.integer(28),
  headlineSmall: stylex.types.integer(24),
  titleLarge: stylex.types.integer(22),
  titleMedium: stylex.types.integer(16),
  titleSmall: stylex.types.integer(14),
  bodyLarge: stylex.types.integer(16),
  bodyMedium: stylex.types.integer(14),
  bodySmall: stylex.types.integer(12),
  labelLarge: stylex.types.integer(14),
  labelMedium: stylex.types.integer(12),
  labelSmall: stylex.types.integer(11),
});

export const expressiveSysGrad = stylex.defineVars({
  displayLarge: stylex.types.integer(0),
  displayMedium: stylex.types.integer(0),
  displaySmall: stylex.types.integer(0),
  headlineLarge: stylex.types.integer(0),
  headlineMedium: stylex.types.integer(0),
  headlineSmall: stylex.types.integer(0),
  titleLarge: stylex.types.integer(0),
  titleMedium: stylex.types.integer(0),
  titleSmall: stylex.types.integer(0),
  bodyLarge: stylex.types.integer(0),
  bodyMedium: stylex.types.integer(0),
  bodySmall: stylex.types.integer(0),
  labelLarge: stylex.types.integer(0),
  labelMedium: stylex.types.integer(0),
  labelSmall: stylex.types.integer(0),
});

export const expressiveSysWdth = stylex.defineVars({
  displayLarge: stylex.types.integer(100),
  displayMedium: stylex.types.integer(100),
  displaySmall: stylex.types.integer(100),
  headlineLarge: stylex.types.integer(100),
  headlineMedium: stylex.types.integer(100),
  headlineSmall: stylex.types.integer(100),
  titleLarge: stylex.types.integer(100),
  titleMedium: stylex.types.integer(100),
  titleSmall: stylex.types.integer(100),
  bodyLarge: stylex.types.integer(100),
  bodyMedium: stylex.types.integer(100),
  bodySmall: stylex.types.integer(100),
  labelLarge: stylex.types.integer(100),
  labelMedium: stylex.types.integer(100),
  labelSmall: stylex.types.integer(100),
});

export const expressiveSysRond = stylex.defineVars({
  displayLarge: stylex.types.integer(0),
  displayMedium: stylex.types.integer(0),
  displaySmall: stylex.types.integer(0),
  headlineLarge: stylex.types.integer(0),
  headlineMedium: stylex.types.integer(0),
  headlineSmall: stylex.types.integer(0),
  titleLarge: stylex.types.integer(0),
  titleMedium: stylex.types.integer(0),
  titleSmall: stylex.types.integer(0),
  bodyLarge: stylex.types.integer(0),
  bodyMedium: stylex.types.integer(0),
  bodySmall: stylex.types.integer(0),
  labelLarge: stylex.types.integer(0),
  labelMedium: stylex.types.integer(0),
  labelSmall: stylex.types.integer(0),
});

export const expressiveSysCrsv = stylex.defineVars({
  displayLarge: stylex.types.integer(0),
  displayMedium: stylex.types.integer(0),
  displaySmall: stylex.types.integer(0),
  headlineLarge: stylex.types.integer(0),
  headlineMedium: stylex.types.integer(0),
  headlineSmall: stylex.types.integer(0),
  titleLarge: stylex.types.integer(0),
  titleMedium: stylex.types.integer(0),
  titleSmall: stylex.types.integer(0),
  bodyLarge: stylex.types.integer(0),
  bodyMedium: stylex.types.integer(0),
  bodySmall: stylex.types.integer(0),
  labelLarge: stylex.types.integer(0),
  labelMedium: stylex.types.integer(0),
  labelSmall: stylex.types.integer(0),
});

export const expressiveSysSlnt = stylex.defineVars({
  displayLarge: stylex.types.integer(0),
  displayMedium: stylex.types.integer(0),
  displaySmall: stylex.types.integer(0),
  headlineLarge: stylex.types.integer(0),
  headlineMedium: stylex.types.integer(0),
  headlineSmall: stylex.types.integer(0),
  titleLarge: stylex.types.integer(0),
  titleMedium: stylex.types.integer(0),
  titleSmall: stylex.types.integer(0),
  bodyLarge: stylex.types.integer(0),
  bodyMedium: stylex.types.integer(0),
  bodySmall: stylex.types.integer(0),
  labelLarge: stylex.types.integer(0),
  labelMedium: stylex.types.integer(0),
  labelSmall: stylex.types.integer(0),
});

export const expressiveSysFill = stylex.defineVars({
  displayLarge: stylex.types.integer(0),
  displayMedium: stylex.types.integer(0),
  displaySmall: stylex.types.integer(0),
  headlineLarge: stylex.types.integer(0),
  headlineMedium: stylex.types.integer(0),
  headlineSmall: stylex.types.integer(0),
  titleLarge: stylex.types.integer(0),
  titleMedium: stylex.types.integer(0),
  titleSmall: stylex.types.integer(0),
  bodyLarge: stylex.types.integer(0),
  bodyMedium: stylex.types.integer(0),
  bodySmall: stylex.types.integer(0),
  labelLarge: stylex.types.integer(0),
  labelMedium: stylex.types.integer(0),
  labelSmall: stylex.types.integer(0),
});

export const expressiveSysHexp = stylex.defineVars({
  displayLarge: stylex.types.integer(0),
  displayMedium: stylex.types.integer(0),
  displaySmall: stylex.types.integer(0),
  headlineLarge: stylex.types.integer(0),
  headlineMedium: stylex.types.integer(0),
  headlineSmall: stylex.types.integer(0),
  titleLarge: stylex.types.integer(0),
  titleMedium: stylex.types.integer(0),
  titleSmall: stylex.types.integer(0),
  bodyLarge: stylex.types.integer(0),
  bodyMedium: stylex.types.integer(0),
  bodySmall: stylex.types.integer(0),
  labelLarge: stylex.types.integer(0),
  labelMedium: stylex.types.integer(0),
  labelSmall: stylex.types.integer(0),
});
